# Configuration de l'image
image:
  repository: wordpress
  tag: "6.5-apache"
  pullPolicy: Always

# Nombre de pods
replicaCount: 1

# Configuration du Service (Réseau)
service:
  type: ClusterIP
  port: 80

# Configuration de la Base de Données (A changer selon votre install)
db:
  host: "10.20.59.16:3306"
  user: "root"
  password: "P@ssw0rd34"
  name: "wordpress"