apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: wordpresss
 namespace: wordpresss
spec:
 rules:
   - host: wordpresss.afpa-devops.lab
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: wordpresss
               port:
                number: 80
