apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpresss
data:
  WORDPRESS_DB_HOST: "mariadb-external"
  WORDPRESS_DB_USER: "wpuser"
  WORDPRESS_DB_NAME: "wordpresss"
  WORDPRESS_TABLE_PREFIX: "wp_"
