# Image officielle
image:
  repository: wordpresss
  tag: "6.5-apache"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80

# Configuration DB (Identique Ã  avant, mais on peut changer le nom de la DB si besoin)
db:
  host: "10.20.59.16:3306"
  user: "wp_user"        # Assurez-vous que cet user existe dans MySQL
  password: "P@ssw0rd34"
  name: "wordpresss"

# INGRESS : C'est ici que tout change
ingress:
  enabled: true
  className: "traefik"
  # Nouvelle URL avec 3 's'
  host: "wordpresss.afpa-devops"

# Configuration du stockage (NFS)
persistence:
  enabled: true
  storageClass: "nfs-static"
  accessMode: ReadWriteMany
  size: "8Gi"
  nfs:
    server: "10.20.59.15"
    path: "/srv/nfs/wordpresss-content"  # Nouveau chemin pour ce chart